### ISSUE TITLE
Epic: Retooling the project

### ISSUE THREAD

**Issue by andrewsosa** [FSU-ACM/Contest-Server#91]
This issue is meant to be a super-issue to discuss at a high level several related changes for this project. The goal is to change several facets of the project at a tool level, not related to source code changes. 

Topics: 
- [ ] Introduce `pipenv` for dependency management (#92)
- [ ] Introduce code linting and formatting (see: #90)
- [ ] Introduce automatic testing (see: #89)
- [ ] Integrate code versioning with Docker image tags
- [ ] Use Travis CI to run linting and formatting checks
- [ ] Use Travis CI to run automated unit/integration/regression tests
- [ ] Use Travis CI to automatically publish versioned Docker images to the Docker Hub
- [ ] Replace Node.js dependencies (Sass, vuepress) with Python alternatives where possible (#93)
- [ ] Switch to object-based configuration for Flask (#94)

The Travis CI issues are related all generally related to #42.
